/**
 * Hidden subcommand `tinkerise __complete <kind>` — emits newline-
 * separated completion candidates consumed by the shell scripts
 * generated by `tinkerise completion <shell>` (D-07, D-09, D-10).
 *
 * Output contract:
 * - stdout: one candidate per line, trailing newline; nothing else.
 * - exit 0 on known kind (even if the candidate set is empty).
 * - throws TinkeriseError ({ code: COMPLETION_UNKNOWN_KIND }) on
 *   unknown kind so handleError() routes it to stderr + non-zero
 *   exit. The shell completion scripts swallow stderr (D-09) so
 *   users never see this in normal use.
 *
 * Registered with Commander's hidden-command option so it does NOT
 * appear in --help, --list, or any docs surface (D-10). Generators in
 * packages/cli/src/completion/* explicitly skip this command name.
 *
 * File-naming exception: `__complete.ts` uses leading underscores
 * intentionally — matches the cobra/clap_complete `__complete`
 * precedent and the user-facing subcommand name. Documented in
 * 34-PATTERNS.md "Shared Patterns / File / module conventions".
 *
 * Trust boundary: the `kind` positional argument is untrusted user
 * input but flows through a closed if-chain of literal string
 * comparisons with the `scaffolders:<category>` suffix validated
 * against a hard-coded allow-list. No spawn, no eval, no FS writes
 * (T-34-04 mitigation).
 */

import type { Command } from 'commander'
import {
  allEnhancementModules,
  getAllScaffolders,
  getScaffoldersByCategory,
  listPresets,
  TinkeriseError,
} from '@tinkerise/core'

const CATEGORIES = ['web', 'backend', 'mobile'] as const
type Category = typeof CATEGORIES[number]

function isCategory(value: string): value is Category {
  return (CATEGORIES as readonly string[]).includes(value)
}

export function registerCompleteCommand(program: Command): void {
  program
    .command('__complete <kind>', { hidden: true })
    .description('Internal: emit completion candidates (consumed by shell scripts)')
    .action(async (kind: string) => {
      const items = await resolveCandidates(kind)
      if (items.length > 0)
        process.stdout.write(`${items.join('\n')}\n`)
    })
}

async function resolveCandidates(kind: string): Promise<string[]> {
  if (kind === 'categories')
    return [...CATEGORIES]

  if (kind === 'enhancements')
    return allEnhancementModules.map(e => e.id)

  if (kind === 'presets')
    return await listPresets()

  if (kind === 'scaffolders')
    return getAllScaffolders().map(s => s.name)

  if (kind.startsWith('scaffolders:')) {
    const category = kind.slice('scaffolders:'.length)
    if (!isCategory(category)) {
      throw new TinkeriseError({
        message: `Unknown completion kind: '${kind}'. Valid scaffolders categories: web, backend, mobile.`,
        code: 'COMPLETION_UNKNOWN_KIND',
        suggestion: 'Valid kinds: scaffolders, scaffolders:<category>, enhancements, presets, categories.',
      })
    }
    return getScaffoldersByCategory(category).map(s => s.name)
  }

  throw new TinkeriseError({
    message: `Unknown completion kind: '${kind}'.`,
    code: 'COMPLETION_UNKNOWN_KIND',
    suggestion: 'Valid kinds: scaffolders, scaffolders:<category>, enhancements, presets, categories.',
  })
}
